main_path:
  root: C:/Users/Codeexia/FinalSemester

test_path:
  root: ${main_path.root}/CPC1 Data/clarity_CPC1_data.test.v1/clarity_CPC1_data
  spin_folder: ${test_path.root}/clarity_data/HA_outputs/test           # Speech in Noise audio
  scenes_folder: ${test_path.root}/clarity_data/scenes                  # Clean speech audio
  ref_file: ${test_path.root}/metadata/CPC1.test.json                   # JSON with listener and scene info
  listeners_file: ${test_path.root}/metadata/listeners.CPC1_all.json    # Listener audiogram data
  stoi_output_file: ${test_path.root}/stoi_scores.json                  # Path to save STOI scores

# Specify the sample rate for resampling audio
sample_rate: 10000

# Configure Hydra's output logging
hydra:
  run:
    dir: ./hydra_files/${now:%Y-%m-%d}/${now:%H-%M-%S}
